AWSTemplateFormatVersion: 2010-09-09
Description: >-
    Creates a DeepLearning Cluster with one Master and a variable number of Workers, using FSx for Lustre and running Horovod model training jobs via MPI.
Parameters:
    VpcCIDR:
        Description: >-
            CIDR range for the VPC
        Type: String
        Default: 192.168.0.0/26
        AllowedPaatter: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    PublicSubnetCIDR:
        Description: >-
            Public Subnet CIDR in VpcCIDR
        Type: String
        Default: 192.168.0.0/27
        AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    PrivateSubnetCIDR:
        Description: >-
            Private Subnet CIDR in VpcCIDR
        Type: String
        Default: 192.168.0.32/27
        AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
Resources:
    DataBucket:
        Type: 'AWS::S3::Bucket'
        Description: >-
            S3 Bucket hosting the training input data, as the backend to FSx Lustre.
    Vpc:
        Type: 'AWS::EC2::VPC'
        Properties:
            CidrBlock: !Ref VpcCIDR
            EnableDnsSupport: 'true'
            EnableDnsHostnames: 'true'
            Tags:
                - Key: Name
                  Value: !Ref 'AWS::StackName'
    PrivateSubnet:
        Type: 'AWS::EC2::Subnet'
        Properties:
            VpcId: !Ref Vpc
            CidrBlock: !Ref PrivateSubnetCIDR
            AvailabilityZone: !Select
              - 0
              - Fn::GetAZs: !Ref 'AWS::Region'
            Tags:
                - Key: Network
                Value: Private
                - Key: Name
                Value: !Ref 'AWS::StackName'
    PublicSubnet:
        Type: 'AWS::EC2::Subnet'
        DependsOn:
        - PrivateSubnet
        Properties:
            VpcId: !Ref Vpc
            CidrBlock: !Ref PublicSubnetCIDR
            AvailabilityZone: !GetAtt 
                - PrivateSubnet
                - AvailabilityZone
            Tags:
                - Key: Network
                Value: Public
                - Key: Name
                Value: !Ref 'AWS::StackName'